#!/bin/bash

set -e

DRV_NAME=r8125
DRV_VERSION=R8125B-VERSION


dkms add -m ${DRV_NAME} -v ${DRV_VERSION}
dkms build -m ${DRV_NAME} -v ${DRV_VERSION}
dkms install -m ${DRV_NAME} -v ${DRV_VERSION}
RESULT=$?


echo "blacklist r8169" >> /etc/modprobe.d/pve-blacklist.conf
echo "r8125" >> /etc/modules
modprobe r8125

#update-initramfs -u -k all
update-initramfs -u

echo "Finished running dkms install steps."

exit $RESULT



